name: Build deb

on:
  push:
    branches:
      - master
  workflow_dispatch: 

jobs:
  build:
    runs-on: ubuntu-24.04
    env:
      TZ: Asia/Shanghai
    steps:
      # Step 0: 简化空间
      #- name: Maximize build space
      #  uses: easimon/maximize-build-space@master
      #  with:
      #    root-reserve-mb: 10240
      #    swap-size-mb: 1024
      #    remove-dotnet: 'true'
      #    remove-android: 'true'
      #    remove-haskell: 'true'
      #    remove-codeql: 'true'
          
      # Step 1: 检出代码     
      - name: Checkout
        uses: actions/checkout@v3
        with:  
          submodules: 'true'

      # Step 2: 安装构建所需的软件包
      - name: Install base package
        run: |
          df -h
          pwd
          ls
          sudo docker rmi $(docker image ls -aq) >/dev/null 2>&1 || true
          sudo rm -rf \
            /usr/share/dotnet /usr/local/lib/android /opt/ghc \
            /usr/local/share/powershell /usr/share/swift /usr/local/.ghcup \
            /usr/lib/jvm || true
          df -h

      # Step 3: 构建 deb 文件
      - name: Build
        run: |
          df -h
          uname -a
          sudo uname -a
          sudo bash build.sh
          mkdir -p artifacts
          find ./ -name "*.deb" -exec cp {} ./artifacts/ \;
          find ./ -name "*.patch" -exec cp {} ./artifacts/ \;
          

      # Step 4: 上传工件
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: pve-edk2-firmware
          path: artifacts/*

      # Step 5: 获取当前时间
      - name: Get current time
        id: current-time
        uses: josStorer/get-current-time@v2.0.2
        with:
          format: YYYYMMDD-HHmmSS
          utcOffset: "+08:00"

      # Step 6: 列出 artifacts 目录中的文件
      - name: List artifacts directory
        run: |
          echo "Listing files in artifacts directory:"
          ls -l artifacts/
          cd artifacts
          

      # Step 7: 创建 GitHub Release
      - name: Create GitHub Releases
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ format('v{0}', steps.current-time.outputs.formattedTime) }}
          release_name: ${{ format('build-{0}', steps.current-time.outputs.formattedTime) }}
          body: |
            build deb
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Step 8: 上传 deb 文件到 Release
      - name: Upload each deb file to release
        run: |
          for file in ${GITHUB_WORKSPACE}/artifacts/*; do
            echo "Uploading $file"
            echo "file=$file" >> $GITHUB_ENV
            # 调用上传动作
            curl -X POST -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
              -H "Content-Type: application/octet-stream" \
              --data-binary @"$file" \
              "https://uploads.github.com/repos/${{ github.repository }}/releases/${{ steps.create_release.outputs.id }}/assets?name=$(basename $file)"
          done
